### ISSUE TITLE
TypeError: can't concat str to bytes when amount is 0

### ISSUE THREAD

**Issue by czelusniakdawid** [sporestack/bitcash#19]
Suppose we have output which includes amount `0` eg:
```
outputs = [('bchtest:qp6lpagexzll90d9cpuk8ukyuxzughsr4upvy465vq', 1000), ('bchtest:qzy7t6pxfqfnad50cxm76dun60qzz5eua57xkqlj07', 0)]
```
If `dest` is string there will be a `TypeError` on the following line:
https://github.com/sporestack/bitcash/blob/master/bitcash/transaction.py#L195
`TypeError: can't concat str to bytes`.

Please make sure that `dest` is always `bytes` eg. by:
`dest.encode()`.

Thank you!

**Comment by teran-mckinney** [comment]
@cyborg0922 @lannocc, with your changes are there any conditons where you can have an unspent output with 0 satoshis?

For regular spending this would be not necessary, is that correct? I think this is more for OP_RETURN type stuff.

Thanks for reporting this. Lots of recent changes I still need to catch up on.

**Comment by lannocc** [comment]
I think I only changed the handling of `message` (try str.encode() first then just assume it's already bytes) and the size of `MESSAGE_LIMIT`, but I've done some other hacking on it locally too so I don't quite remember everything I touched. I'll look into it this weekend since I also need to pull down the latest merge.

**Comment by cyborg0922** [comment]
I'm at work so can't read code but I think what may be going on here is that if you directly create a txn without using sanitize_tx()... then you skip the part that iannoc added and then construct_output_block () throws this error in the op_return section because it's trying to append dest to op_return bytes. Bitcash was designed to only flow through sanitize_tx (). But I think it's an easy fix by just adding a similar encode() step.

I've had this error code before when plugging in messages as strings (by doing all the sanitize tx stuff manually and plugging in outputs as above).

**Comment by czelusniakdawid** [comment]
@cyborg0922 yes, I call `create_p2pkh_transaction` function directly and maybe that's the point. If library is designed in a way that calling `sanitize_tx_data` is a necessary step then this issue can be closed. Thank you for your help!

**Comment by cyborg0922** [comment]
@czelusniakdawid I kinda agree that it'd be good if `create_p2pkh_transaction` worked without error codes aswell. All I meant is that the original creator of "bit" seemingly intended for us to use the Wallet.py functions under the `PrivateKey` class and `PrivateKeyTest` class.
- e.g. `my_key.Create_transaction` always runs a `sanitize_tx()` before it returns `create_p2pkh_transaction()` as the last step.

- Doesn't mean we can't change it or make it better! :)

So if we added an encode step in there; What I am not sure on is what the default behavior should be for when someone places a 0 amount output into construct_output_block() (as in the OP)... 

option 1) do we assume that they mean for it to be interpreted as a utf-8 encoded "message" (i.e. with the automatic pushdata op code at the start?) - Probably I would say. 

Or instead, would it imply some more "advanced stuff" in which case you'd want it to default to the "custom_pushdata == True" case... lets user specify op_push codes and everything... (but if this were the case, I think they'd already have it packaged as bytes).

These decisions are not up to me though. Just spit-balling.
