### ISSUE TITLE
how can I get the privatekey of key()'s address

### ISSUE THREAD

**Issue by ztlovemst11** [sporestack/bitcash#22]
I want to keep my address's privatekey

**Comment by lannocc** [comment]
There is `to_hex()`, `to_wif()`, `to_pem()`, etc. in the Key (PrivateKey) class.

**Comment by ztlovemst11** [comment]
thank a lot

**Comment by ztlovemst11** [comment]
@lannocc I am sorry , something is still make me confused 
when I use "key = Key()"
It return a statement "<PrivateKey: bitcoincash:qre5yyzq2e3fq60vwk5qkk6n6qjxqkqe4u9jlwm7e8>"
is it use "bitcoincash:qre5yyzq2e3fq60vwk5qkk6n6qjxqkqe4u9jlwm7e8" as a seed to generata a privatekey?

**Comment by ztlovemst11** [comment]
is it safe for us?
Will the private key leak out?

**Comment by lannocc** [comment]
@ztlovemst11: `key = Key()` creates a new private key, as you discovered. Use `key.address` to get the public address. With the methods I indicated above, you can get the private key in different formats. It will be up to you to save them securely for future use. But let's assume you used `key.to_hex()` to get the private key hex value. Then, in the future you can do `key = Key.from_hex(your_private_key)` to use it again, and the address from `key.address` will be the same as it was the first time. I can't really comment on the address returned on testnet because I've not done much on testnet, but I do know the same address can have different formats so maybe that's what you're seeing.

**Comment by ztlovemst11** [comment]
thank you a lot , I get it

**Comment by lannocc** [comment]
Looking at the code some more, there is `PrivateKeyTestnet` that you should probably be using for testnet stuff. `Key` is an alias for `PrivateKey` which is meant for mainnet. Both `PrivateKeyTestnet` and `PrivateKey` (aka `Key`) have the same methods.

**Comment by lannocc** [comment]
@ztlovemst11 Testnet addresses will begin with `bchtest:`

**Comment by ztlovemst11** [comment]
@lannocc  Can you help me see what is going on with this problem?

**Comment by lannocc** [comment]
that ticket is closed
