### ISSUE TITLE
Broadcast of raw transaction fails on testnet

### ISSUE THREAD

**Issue by joemarct** [sporestack/bitcash#3]
I am getting `ConnectionError: Transaction broadcast failed, or Unspents were already used.` when trying to broadcast a transaction. I'm sure I have unspent transaction output when I did this.

**Comment by teran-mckinney** [comment]
Ah, yes. So currently testnet only has one API, the Blockdozer API. It goes down fairly often. I would wait and try it again. Most likely that is the reason. But, kind of wonder if we could add some kind of debug logging to give more insight as it's really vague about that.

I want to add more APIs but right now we are in an awkward transitionary phase with the Bitcoin Cash address format. If we can stick to just Insight APIs that would be ideal.

If you poke around in the tests folder, there's some other testnet private keys you can play with. Might actually be worth running the tests to see what works and what doesn't. Now a lot of it is still broken since the port. I have some stuff to fix.

**Comment by teran-mckinney** [comment]
@joemarct have you had a chance to look into this more?

**Comment by teran-mckinney** [comment]
Good news. I actually stumbled across a big issue with testnet.

blockdozer's testnet subdomain switched to HTTPS. They started doing redirects from HTTP to HTTPS. The Python requests library would see the 302 then do a GET on the new URL. Seems kind of like a buggy, weird behavior.

Anyway, I changed the URL so it should work now. I haven't pushed up 0.4.4, but if you are working from the git master you should be alright. Let me know if you want me to push up 0.4.4 and I can do that.

https://github.com/sporestack/bitcash/commit/f7733deda0c80001388fab1faa26c57139434d3d#diff-49b52520d0aaec289cbca1ba77eac3ecR122

**Comment by teran-mckinney** [comment]
More on this in #5. I will close this out and we can continue there if need be.

Thanks!
