### ISSUE TITLE
any possibilities to add dash,ltc or eth? 

### ISSUE THREAD

**Issue by expired-brain** [sporestack/bitcash#6]

**Comment by teran-mckinney** [comment]
As I said [here](https://github.com/ofek/bit/issues/16#issuecomment-376197013), it's better to fork bit or bitcash and add support rather than try to put it all into one library. That may be possible a ways down the road, but it would be a lot of work to support multiple currencies.

I am certainly curious about all of the currencies you've listed. At this time I am not working on making any libraries for them. Forking bit to bitcash was tricky. Litecoin might be doable, but Dash or Ethereum would likely be even trickier. It's definitely possible, just a lot of work.

**Comment by teran-mckinney** [comment]
Going to close this for now. Let me know if you have any more questions.
