### ISSUE TITLE
Balance x is less than y (including fee)

### ISSUE THREAD

**Issue by jbertman** [sporestack/bitcash#8]
First of all, fantastic port of the bit library, things seem to be coming along nicely. This may fit into the dynamic fees problem, but I wanted to see if there was anything I could do to fix it in the meantime.

I have an app that receives transactions and processes the balances to result in changes for the application. The balance is then marked as processed and is (eventually) moved to a cold storage wallet. Often this is the entire balance of that wallet. My code looks something like:
```python
processed_balance = get_processed_balance()  # This is often the full balance of the wallet 
if processed_balance > 0:
    key = wif_to_key(get_priv_key())
    print(key.get_unspents())
    outputs = [
        (
		settings.COLD_STORAGE_WALLET,
		processed_balance,
		'bch'
	),
    ]
    key.send(outputs, fee=1)
```
And the output:
```python
# Debug printing the unspents
[Unspent(amount=199322, confirmations=82, script='someScriptKey', txid='sometxid', txindex=1)]
# The resulting error
Traceback (most recent call last):
  File "actions.py", line 62, in move_to_cold_storage
    key.send(outputs, fee=1)
  File "/venv/lib/python3.5/site-packages/bitcash/wallet.py", line 291, in send
    outputs, fee=fee, leftover=leftover, combine=combine, message=message, unspents=unspents
  File "/venv/lib/python3.5/site-packages/bitcash/wallet.py", line 249, in create_transaction
    compressed=self.is_compressed()
  File "/venv/lib/python3.5/site-packages/bitcash/transaction.py", line 155, in sanitize_tx_data
    'fee).'.format(total_in, total_out))
bitcash.exceptions.InsufficientFunds: Balance 199322 is less than 199548 (including fee).
```
Should I be getting the total fee for the transaction beforehand and subtracting it from the total to send? What is the best way to go about doing that?

Thanks in advance!

**Comment by teran-mckinney** [comment]
Hi!

I'm glad you've been finding it useful. Thanks for writing in.

For sweeps, I've just been doing this: https://github.com/teran-mckinney/walkingliberty-python/blob/master/walkingliberty/__init__.py#L92

Sounds like you aren't always sweeping, though. So your outputs less have to be less than the balance of the wallet. The fees don't get taken from the outputs. The leftover_address is where the remainder should be sent after fees. You can't have outputs of the full balance, there's no logic in the library to remove fees from the outputs. So if you want to sweep the whole thing, you have to calculate the fees in advance, or you can just do a sweep like that.

All of the inputs have their amount accounted for. Whatever isn't an output in that is a fee. A change address is usually where you want the remainder to go.

Take a look here at the fees and outputs: https://github.com/sporestack/bitcash/blob/master/bitcash/wallet.py#L501

Been a while since I worked on the library last so hopefully am explaining it right. Let me know if this makes sense or not.

**Comment by jbertman** [comment]
Thanks for getting back so quickly! That makes good sense. I'll probably end up doing sweeps the same way you are. 

Thanks for the clarification and pointers. I'll close this for now since it was really just a question, feel free to reopen as needed!
