### ISSUE TITLE
Can't get address or balance on testnet

### ISSUE THREAD

**Issue by lazygreed** [sporestack/bitcash#9]
When I call key.address parameter, it returns PrivateKey, not address (found cashaddress solution)

also key.balance everytime returns 0
when trying to call key.get_unspents() after transaction, it crashes
```
File "/home/l4zygreed/Templates/btc_py/venv/lib/python3.6/site-packages/bitcash/wallet.py", line 489, in get_unspents
    self.unspents[:] = NetworkAPI.get_unspent_testnet(self.address)
  File "/home/l4zygreed/Templates/btc_py/venv/lib/python3.6/site-packages/bitcash/network/services.py", line 315, in get_unspent_testnet
    return api_call(address)
  File "/home/l4zygreed/Templates/btc_py/venv/lib/python3.6/site-packages/bitcash/network/services.py", line 157, in get_unspent_testnet
    for tx in r.json()
  File "/home/l4zygreed/Templates/btc_py/venv/lib/python3.6/site-packages/bitcash/network/services.py", line 157, in <listcomp>
    for tx in r.json()
KeyError: 'scriptPubKey'
```

**Comment by lazygreed** [comment]
sorry, expected legacy (shorter) type of address, like in original bit repo

`key.get_unspets` still cryshing untils first confirmation on network
and `key.balance` still 0
```
>>> key.get_unspents()
[Unspent(amount=200000000, confirmations=8, script='76a9141944c73fec145bd87f3e427921568d21a95694ea88ac', txid='eabf0b3e4d4d806c1a0f4dd111cbc5c1dbfe6a7a6fdbcbfe760c709c23e9b079', txindex=1)]
>>> key.balance
0
```

founded another problem, I can't transfer funds
```
>>> key.create_transaction([], leftover='mqFJqi8SMevMdALqDdUsgiW3FEjVXYqWsv')
'010000000179b0e9239c700c76fecbdb6f7a6afedbc1c5cb11d14d0f1a6c804d4d3e0bbfea010000006a47304402201f3d47f09710d9b556d3175694637dfef838a1fb3cddcdcee1ec37870f3e352e022031eb23a8cdbeb249e1355badef19aff5a68f967f9987385dc2f8e660601015984121039990a14e6b7ad0237e1dd5801e277938d9642794b900a8e8fcec220417496b81ffffffff0100bfeb0b000000001976a9146abbc0d28291128f3b70460a3c0e02e2393bd3cd88ac00000000'
>>> key.transactions
[]
```

**Comment by teran-mckinney** [comment]
> key.get_unspets still cryshing until first confirmation on network

This is going to depend on the behavior of the one (or two?) upstream testnet APIs in use.

> founded another problem, I can't transfer funds

key.transactions will only show a list of transactions that have been on the network. I could be wrong on that, but creating a transaction (which only returns the hex and nothing else) definitely won't update that. You'll have to send to expect any change there. Even then, that feature could be broken, not really sure.

> ConnectionError: Transaction broadcast failed, or Unspents were already used.

This error usually comes upstream. I want to improve logging here so that there's at least some warning with what happened.

I'm going to dig into this some more. I would try to stick with the cashaddr format if you can, it's what the API is designed around.

I use bitcash heavily on mainnet but some features are untested by me. If you see insufficient testing you can push up a PR with more test cases.

**Comment by teran-mckinney** [comment]
> KeyError: 'scriptPubKey'

This is coming from tbch.blockdozer.com. I am making a change to ignore keys without 'scriptPubKey'.

**Comment by teran-mckinney** [comment]
Alright, I just pushed a commit (but no release) with some improvements. The Blockdozer API made some changes, breaking TX sends for testnet, and changing the unspent format. They don't have pubscripthash on unconfirmed transactions now. We could allow that to be set to None, but may cause other problems.

You may want to contact Blockdozer and get them in the loop on this thread. Not sure how much of this affects mainnet and not just testnet.

**Comment by teran-mckinney** [comment]
Also, `key.balance` is only accurate after getting unspents. Or maybe doing a send. It starts at 0, maybe not the best behavior.

**Comment by teran-mckinney** [comment]
Pushed one more commit. Tests can pass now if the timing is right.
